plugins { id 'com.android.application' }
android {
    namespace 'com.jayan.os'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jayan.os'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.8'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
